name: Testing - User Service

on:
  pull_request:
    paths:
      - "user-service/**"

  workflow_call:
    secrets:
      DATABASE_URL:
        required: true

jobs:
  lint:
    uses: "./.github/workflows/lint-user-service.yml"
  test:
    name: Run Tests for User Service
    runs-on: ubuntu-latest
    needs: ["lint"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./user-service
        run: npm install

      - name: Create .env.test File
        working-directory: ./user-service
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test
          echo "NODE_ENV=testing" >> .env.test

      - name: Generate Coverage Report
        working-directory: ./user-service
        run: npm run test:coverage
